default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  username: khataev
  password:

development:
  <<: *default
  database: vmnet_development

test:
  <<: *default
  database: vmnet_test

#production:
#    adapter: mysql2
#    host: mysql65.1gb.ru
#    database: gb_wpkhataev
#    username: gb_wpkhataev
#    password: ba534f6a4tyu
